
name: Node.js CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']
  repository_dispatch:
    types: [contentful.deploy]
  # schedule:
  #   - cron: '0 0 * * *'  # dar trigger às 00:00 de todos os dias da semana
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npx prettier . --write 
      - run: npx prettier . --check
      - run: npm test
      - run: npm run lint

  deploy-direct:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' || github.event_name == 'schedule' || github.event_name == 'repository_dispatch'
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - name: deploy
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      
      - run: npm run build
        env: 
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      - run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID}} --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --prod


